// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type IsAny<T> = 0 extends 1 & T ? true : false
type InjectionType<A extends Plugin> = IsAny<A> extends true ? unknown : A extends Plugin<infer T> ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/plugins/revive-payload.client.js").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/plugins/unhead.js").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/pages/runtime/plugins/router.js").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/plugins/payload.client.js").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/plugins/revive-payload.server.js").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.5.4_magicast@0.3.4_rollup@4.21.0_typescript@5.5.4_vue@3.4.38_typescript@5.5.4_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js").default> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js").default>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
