
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AccountHeader': typeof import("../components/AccountHeader.vue")['default']
    'LogoutButton': typeof import("../components/LogoutButton.vue")['default']
    'CommonContentLoader': typeof import("../components/common/ContentLoader.vue")['default']
    'CommonImageLoader': typeof import("../components/common/ImageLoader.vue")['default']
    'CommonSpinner': typeof import("../components/common/Spinner.vue")['default']
    'CommonButton': typeof import("../components/common/button/Button.vue")['default']
    'CommonButtonLine': typeof import("../components/common/button/Line.vue")['default']
    'CommonButtonLineBodyInfo': typeof import("../components/common/button/LineBodyInfo.vue")['default']
    'CommonButtonLineWithImg': typeof import("../components/common/button/LineWithImg.vue")['default']
    'CommonLine': typeof import("../components/common/line/Line.vue")['default']
    'IconsZkSync': typeof import("../components/icons/ZkSync.vue")['default']
    'TokenAmount': typeof import("../components/token/TokenAmount.vue")['default']
    'TokenAmountLoader': typeof import("../components/token/TokenAmountLoader.vue")['default']
    'TokenImage': typeof import("../components/token/TokenImage.vue")['default']
    'TokenLine': typeof import("../components/token/TokenLine.vue")['default']
    'ViewsConnect': typeof import("../components/views/Connect.vue")['default']
    'ViewsLoading': typeof import("../components/views/Loading.vue")['default']
    'ViewsLogin': typeof import("../components/views/Login.vue")['default']
    'ViewsConfirmation': typeof import("../components/views/confirmation/Confirmation.vue")['default']
    'ViewsConfirmationMethodNotSupported': typeof import("../components/views/confirmation/MethodNotSupported.vue")['default']
    'ViewsConfirmationRequestAccounts': typeof import("../components/views/confirmation/RequestAccounts.vue")['default']
    'ViewsConfirmationRequestSession': typeof import("../components/views/confirmation/RequestSession.vue")['default']
    'ViewsConfirmationSend': typeof import("../components/views/confirmation/Send.vue")['default']
    'NuxtWelcome': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAccountHeader': typeof import("../components/AccountHeader.vue")['default']
    'LazyLogoutButton': typeof import("../components/LogoutButton.vue")['default']
    'LazyCommonContentLoader': typeof import("../components/common/ContentLoader.vue")['default']
    'LazyCommonImageLoader': typeof import("../components/common/ImageLoader.vue")['default']
    'LazyCommonSpinner': typeof import("../components/common/Spinner.vue")['default']
    'LazyCommonButton': typeof import("../components/common/button/Button.vue")['default']
    'LazyCommonButtonLine': typeof import("../components/common/button/Line.vue")['default']
    'LazyCommonButtonLineBodyInfo': typeof import("../components/common/button/LineBodyInfo.vue")['default']
    'LazyCommonButtonLineWithImg': typeof import("../components/common/button/LineWithImg.vue")['default']
    'LazyCommonLine': typeof import("../components/common/line/Line.vue")['default']
    'LazyIconsZkSync': typeof import("../components/icons/ZkSync.vue")['default']
    'LazyTokenAmount': typeof import("../components/token/TokenAmount.vue")['default']
    'LazyTokenAmountLoader': typeof import("../components/token/TokenAmountLoader.vue")['default']
    'LazyTokenImage': typeof import("../components/token/TokenImage.vue")['default']
    'LazyTokenLine': typeof import("../components/token/TokenLine.vue")['default']
    'LazyViewsConnect': typeof import("../components/views/Connect.vue")['default']
    'LazyViewsLoading': typeof import("../components/views/Loading.vue")['default']
    'LazyViewsLogin': typeof import("../components/views/Login.vue")['default']
    'LazyViewsConfirmation': typeof import("../components/views/confirmation/Confirmation.vue")['default']
    'LazyViewsConfirmationMethodNotSupported': typeof import("../components/views/confirmation/MethodNotSupported.vue")['default']
    'LazyViewsConfirmationRequestAccounts': typeof import("../components/views/confirmation/RequestAccounts.vue")['default']
    'LazyViewsConfirmationRequestSession': typeof import("../components/views/confirmation/RequestSession.vue")['default']
    'LazyViewsConfirmationSend': typeof import("../components/views/confirmation/Send.vue")['default']
    'LazyNuxtWelcome': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AccountHeader: typeof import("../components/AccountHeader.vue")['default']
export const LogoutButton: typeof import("../components/LogoutButton.vue")['default']
export const CommonContentLoader: typeof import("../components/common/ContentLoader.vue")['default']
export const CommonImageLoader: typeof import("../components/common/ImageLoader.vue")['default']
export const CommonSpinner: typeof import("../components/common/Spinner.vue")['default']
export const CommonButton: typeof import("../components/common/button/Button.vue")['default']
export const CommonButtonLine: typeof import("../components/common/button/Line.vue")['default']
export const CommonButtonLineBodyInfo: typeof import("../components/common/button/LineBodyInfo.vue")['default']
export const CommonButtonLineWithImg: typeof import("../components/common/button/LineWithImg.vue")['default']
export const CommonLine: typeof import("../components/common/line/Line.vue")['default']
export const IconsZkSync: typeof import("../components/icons/ZkSync.vue")['default']
export const TokenAmount: typeof import("../components/token/TokenAmount.vue")['default']
export const TokenAmountLoader: typeof import("../components/token/TokenAmountLoader.vue")['default']
export const TokenImage: typeof import("../components/token/TokenImage.vue")['default']
export const TokenLine: typeof import("../components/token/TokenLine.vue")['default']
export const ViewsConnect: typeof import("../components/views/Connect.vue")['default']
export const ViewsLoading: typeof import("../components/views/Loading.vue")['default']
export const ViewsLogin: typeof import("../components/views/Login.vue")['default']
export const ViewsConfirmation: typeof import("../components/views/confirmation/Confirmation.vue")['default']
export const ViewsConfirmationMethodNotSupported: typeof import("../components/views/confirmation/MethodNotSupported.vue")['default']
export const ViewsConfirmationRequestAccounts: typeof import("../components/views/confirmation/RequestAccounts.vue")['default']
export const ViewsConfirmationRequestSession: typeof import("../components/views/confirmation/RequestSession.vue")['default']
export const ViewsConfirmationSend: typeof import("../components/views/confirmation/Send.vue")['default']
export const NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAccountHeader: typeof import("../components/AccountHeader.vue")['default']
export const LazyLogoutButton: typeof import("../components/LogoutButton.vue")['default']
export const LazyCommonContentLoader: typeof import("../components/common/ContentLoader.vue")['default']
export const LazyCommonImageLoader: typeof import("../components/common/ImageLoader.vue")['default']
export const LazyCommonSpinner: typeof import("../components/common/Spinner.vue")['default']
export const LazyCommonButton: typeof import("../components/common/button/Button.vue")['default']
export const LazyCommonButtonLine: typeof import("../components/common/button/Line.vue")['default']
export const LazyCommonButtonLineBodyInfo: typeof import("../components/common/button/LineBodyInfo.vue")['default']
export const LazyCommonButtonLineWithImg: typeof import("../components/common/button/LineWithImg.vue")['default']
export const LazyCommonLine: typeof import("../components/common/line/Line.vue")['default']
export const LazyIconsZkSync: typeof import("../components/icons/ZkSync.vue")['default']
export const LazyTokenAmount: typeof import("../components/token/TokenAmount.vue")['default']
export const LazyTokenAmountLoader: typeof import("../components/token/TokenAmountLoader.vue")['default']
export const LazyTokenImage: typeof import("../components/token/TokenImage.vue")['default']
export const LazyTokenLine: typeof import("../components/token/TokenLine.vue")['default']
export const LazyViewsConnect: typeof import("../components/views/Connect.vue")['default']
export const LazyViewsLoading: typeof import("../components/views/Loading.vue")['default']
export const LazyViewsLogin: typeof import("../components/views/Login.vue")['default']
export const LazyViewsConfirmation: typeof import("../components/views/confirmation/Confirmation.vue")['default']
export const LazyViewsConfirmationMethodNotSupported: typeof import("../components/views/confirmation/MethodNotSupported.vue")['default']
export const LazyViewsConfirmationRequestAccounts: typeof import("../components/views/confirmation/RequestAccounts.vue")['default']
export const LazyViewsConfirmationRequestSession: typeof import("../components/views/confirmation/RequestSession.vue")['default']
export const LazyViewsConfirmationSend: typeof import("../components/views/confirmation/Send.vue")['default']
export const LazyNuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.13.0_@parcel+watcher@2.4.1_@types+node@18.16.9_eslint@9.9.0_jiti@1.21.6__ioredis@5.4.1_m7faqoqwd236wevess32z4lbly/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
