// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/26/2024, 2:04:26 PM
const configMerger = require("/Users/sf/github/matter-labs/zksync-account-sdk/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.4_rollup@4.21.0_ts-node@10.9.2_@swc+core@1.5.29_@swc+_jmr5mer2brekpgxu6xjc6szw4y/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/plugins/**/*.{js,ts,mjs}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/composables/**/*.{js,ts,mjs}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/utils/**/*.{js,ts,mjs}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sf/github/matter-labs/zksync-account-sdk/apps/gateway/app.config.{js,ts,mjs}"] }));

module.exports = config
